### ISSUE TITLE
REPORTE DE HILOS WINDOWS

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-companion-ai#1]
[REPORTE_HILOSWINDOWS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-companion-ai/files/15133450/REPORTE_HILOSWINDOWS.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenas tardes compañeras, muy bien hecho,  20 de 20%, felicidades.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
